In [10]:
# -*-coding:utf-8-*-
# Edited by bighead 19-2-11

import pandas as pd
import numpy as np
from time import time
from utils import get_train_data, get_hog_feature, get_test_data
from sklearn.linear_model import LogisticRegression

In [11]:
########## Load the train dataset
print("loading training data")
load_start = time()
Y, X = get_train_data("data/train.csv")
X = get_hog_feature(X)
print("finish, cost: {} seconds".format(time() - load_start))

loading training data
finish, cost: 6.14407491684 seconds

In [12]:
########## build and fit the logistic regression model from sklearn
model = LogisticRegression()
model.fit(X, Y)

/home/bighead/.local/lib/python2.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [13]:
########## Load the test dataset
print("loading test data")
load_start = time()
X_test = get_test_data("data/test.csv")
X_test = get_hog_feature(X_test)
print("finish, cost: {} seconds".format(time() - load_start))

loading test data
finish, cost: 3.85923099518 seconds

In [14]:
########## Predict the testset
print("\npredict.....")
predict_start = time()
predict = model.predict(X_test)
print("finish, cost: {} seconds".format(time() - predict_start))

predict.....
finish, cost: 0.0702278614044 seconds

In [15]:
print(predict)

[2 0 9 ... 3 9 2]

In [21]:
########## Submit
submit_data = pd.DataFrame(columns=["Label"])
submit_data["Label"] = predict
submit_data.insert(0, "ImageID", range(1, 1+len(predict)))
submit_data.to_csv('submit.csv', index=False)
submit_data

       ImageID  Label
0            1      2
1            2      0
2            3      9
3            4      0
4            5      3
5            6      7
6            7      0
7            8      3
8            9      0
9           10      3
10          11      5
11          12      7
12          13      4
13          14      0
14          15      4
15          16      3
16          17      3
17          18      1
18          19      9
19          20      0
20          21      9
21          22      1
22          23      1
23          24      5
24          25      7
25          26      4
26          27      2
27          28      7
28          29      4
29          30      7
...        ...    ...
27970    27971      5
27971    27972      0
27972    27973      4
27973    27974      8
27974    27975      0
27975    27976      3
27976    27977      6
27977    27978      0
27978    27979      1
27979    27980      9
27980    27981      3
27981    27982      1
27982    27983      1
27983    27984      0
27984    27985      4
27985    27986      5
27986    27987      2
27987    27988      2
27988    27989      9
27989    27990      6
27990    27991      7
27991    27992      6
27992    27993      1
27993    27994      9
27994    27995      7
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]